// abstract base of gpb classes
#pragma once
#include <memory>
#include <iostream>
#include <vector>
#include <utility>
#include <fstream>
#include <gpb/gpbFile.hpp>
#include <stdint.h>
namespace libgranturismo
{
	/// @brief enum defining the version of gpb this file is
	typedef enum {
		GPB2,
		GPB3
	} gpbType;
	/// @brief base of all GPB versions
	class gpbBase {
	public:
		/// @brief type of GPB this is
		gpbType type;
		/// @brief list of files in the .gpb
		/// @details generated by read()
		/// @details access by iterating over and using .length, .name, .data
		std::vector<gpbFile*> files;
	private:
		/// @brief read the GPB from a filename, version dependent
		virtual int read(std::string filename, int endian) = 0;
	};
	/// @brief read a GPB from a file, no matter the version or endianness
	/// @return smart pointer to the GPB object, simply use -> to access the files inside
	std::unique_ptr<gpbBase> readGpbFromFile(std::string filename);
}